dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=hypercore
    - RUST_BACKTRACE=1

matrix:
  include:
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl TYPE=static
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      rust: nightly
      os: osx
    - env: TARGET=x86_64-unknown-freebsd DISABLE_TESTS=1
      rust: nightly

before_install:
  - set -e

install:
  - sh scripts/install.sh
  - source ~/.cargo/env || true

script:
  - bash scripts/script.sh

after_script: set +e

before_deploy:
  - sh scripts/before_deploy.sh

deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  api_key:
    secure: "AnOoCDeyFt1pLqoOosJu4sv9R+UCeeO1CfLHxNXdbVLE1DN3+0gSsuLpNW/5tkkqckRR9AS5+cx2xj9j/EUtebLzH/uUshsKGx/PKZgIkv+AB+2r/EZVWa5J1vGUPmplZHAmEnihcRGFdHAf7PiLGPfVG6V12oRC4MEKS8zeK6zmyKUPJHeT8y5AGMQikAsD3OPxG5WHFM1sRbGswzbQX8JHsZFkgsuXBvfXnnO/GJPG0JA2gVx31hOaGiLL6x3hHVf/CQfOjUjjPTqjMTGQkR2Qsn607KB7Az32ymtayPzC65BWtDu2PCCXRHS5aebBbhb5/jJ1GL2LrQ8wzYB9IbW6qo49nWFG093UE/Hwf0APDt9qt5YjLSOqDniyIuqKxTsh8uc6aWjGR4jT+bah4tF7Qg8su0MfwSbuVYmhxqYYN7IUmrynAskVBn6p2hE2buZHZe1PTFqpW9Jrpm4koPl/HmASujiyBPcAojUAXJsiGLeAH+pMXKpFMxx86CCAoPA1tzr1qP8Zy+hd5tY7AgMJdt1ri3L+G3VqjxwrnQK568EnsFji5nyMnejgcDPqsnVp9NisORm8yI+1Vv3mT4FEY3OTtrN4Obf00zZ99XyudmtKwqU5BnTKr6qqXv/jVKZ1Ara32uUncYpe01bBX0ZQtr/x7dbfSo4RYsBS7zo="
  on:
    tags: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
    on_failure: never
