[package]
name = "hypercore"
version = "0.1.0"
authors = ["bltav"]
repository = "https://github.com/bltavares/rust-over-jna-example"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
